[package]
name = "steingass-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["blocking"] }
scraper = "0.18.1"
tempfile = "3.10.0"
