[package]
name = "steingass-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
abjad = "0.5.0"
anyhow = "1.0.98"
regex = "1.11.1"
reqwest = { version = "0.12.15", features = ["blocking"] }
rusqlite = { version = "0.35.0", features = ["bundled"] }
scraper = "0.23"
tempfile = "3.20.0"
