[package]
name = "steingass-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
abjad = "0.5.0"
anyhow = "1.0.86"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["blocking"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
scraper = "0.19"
tempfile = "3.10.1"
